DROP TABLE MAKERS CASCADE CONSTRAINTS;
DROP TABLE MANAGERS CASCADE CONSTRAINTS;
DROP TABLE PUBLISHERS CASCADE CONSTRAINTS;
DROP TABLE STUDIOS CASCADE CONSTRAINTS;
DROP TABLE ARTISTS CASCADE CONSTRAINTS;
DROP TABLE MEMBERS CASCADE CONSTRAINTS;
DROP TABLE DISCS CASCADE CONSTRAINTS;
DROP TABLE SONGS CASCADE CONSTRAINTS;
DROP TABLE TRACKS CASCADE CONSTRAINTS;
DROP TABLE ALBUMS CASCADE CONSTRAINTS;
DROP TABLE SINGLES CASCADE CONSTRAINTS;
DROP TABLE RANKINGS CASCADE CONSTRAINTS;
DROP TABLE SLEEVES CASCADE CONSTRAINTS;
DROP TABLE RADIOS CASCADE CONSTRAINTS;
DROP TABLE PLAYBACKS CASCADE CONSTRAINTS;
DROP TABLE CLIENTS CASCADE CONSTRAINTS;
DROP TABLE SALE_LINE CASCADE CONSTRAINTS;

CREATE TABLE MAKERS(
mk_name 	VARCHAR2(50), 
mk_address	VARCHAR2(80) NOT NULL,
CONSTRAINT PK_MAKERS PRIMARY KEY(mk_name)
);

CREATE TABLE MANAGERS(
m_name 	VARCHAR2(50), 
m_surn1 VARCHAR2(50), 
m_surn2	VARCHAR2(50), 
m_phone	NUMBER(9) NOT NULL,
CONSTRAINT PK_MANAGERS PRIMARY KEY(m_name, m_surn1)
);

CREATE TABLE PUBLISHERS(
 p_name		VARCHAR2(50), 
 pub_phone	NUMBER(9) NOT NULL,  
CONSTRAINT PK_PUBLISHERS PRIMARY KEY(p_name)
);

CREATE TABLE STUDIOS(
s_name 		VARCHAR2(50), 
s_adress	VARCHAR2(80) NOT NULL, 
t_name 		VARCHAR2(50) NOT NULL, 
t_surname1 	VARCHAR2(50) NOT NULL, 
t_surname2	VARCHAR2(50),
CONSTRAINT PK_STUDIOS PRIMARY KEY(s_name)
);

CREATE TABLE ARTISTS(
name 		VARCHAR2(50),
nationality VARCHAR2(50) NOT NULL, 
language 	VARCHAR2(50) NOT NULL,
CONSTRAINT PK_ARTISTS PRIMARY KEY(name)
);

CREATE TABLE MEMBERS (
group_name 		VARCHAR2(50),
role		 	VARCHAR2(50) NOT NULL, 
name 		    VARCHAR2(50) NOT NULL,
start_g			DATE NOT NULL,
end_g				DATE,
CONSTRAINT PK_MEMBERS PRIMARY KEY(group_name, role, name),
CONSTRAINT FK_MEMBERS FOREIGN KEY(group_name) REFERENCES ARTISTS ON DELETE CASCADE
);


CREATE TABLE DISCS(
ISVN       NUMBER(8),
artist     VARCHAR2(50) NOT NULL,
format     VARCHAR2(1) NOT NULL,
speed      VARCHAR2(10) NOT NULL,
hole       VARCHAR2(10) NOT NULL,
color      VARCHAR2(20) NOT NULL,
album      VARCHAR2(100) NOT NULL,
rel_date   DATE NOT NULL,
publisher  VARCHAR2(50) NOT NULL,
mng_name   VARCHAR2(50) NOT NULL,
mng_surn1  VARCHAR2(50) NOT NULL,
mk1_comp   VARCHAR2(50) NOT NULL,
mk2_comp   VARCHAR2(50) NOT NULL,
CONSTRAINT PK_DISCS PRIMARY KEY(ISVN),
CONSTRAINT FK_DISCS1 FOREIGN KEY(artist) REFERENCES ARTISTS ON DELETE CASCADE,
CONSTRAINT FK_DISCS2 FOREIGN KEY(mk1_comp) REFERENCES MAKERS,
CONSTRAINT FK_DISCS3 FOREIGN KEY(mk2_comp) REFERENCES MAKERS,
CONSTRAINT FK_DISCS4 FOREIGN KEY(mng_name,mng_surn1) REFERENCES MANAGERS,
CONSTRAINT FK_DISCS5 FOREIGN KEY(publisher) REFERENCES PUBLISHERS,
CONSTRAINT CH_DISCS CHECK (format IN ('S', 'L'))
);

CREATE TABLE SONGS (
title      VARCHAR2(100),
writer     VARCHAR2(100),
CONSTRAINT PK_SONGS PRIMARY KEY(title, writer)
);

CREATE TABLE TRACKS (
ISVN       	NUMBER(8),
trackN		NUMBER(2) NOT NULL,
side		VARCHAR2(1) NOT NULL, 
title_s		VARCHAR2(100) NOT NULL,
writer		VARCHAR2(100) NOT NULL, 
duration 	NUMBER(5) NOT NULL,
studio     	VARCHAR2(50) NOT NULL,
CONSTRAINT PK_TRACKS PRIMARY KEY(ISVN, trackN, side), 
CONSTRAINT FK_TRACKS1 FOREIGN KEY (title_s, writer) REFERENCES SONGS,
CONSTRAINT FK_TRACKS2 FOREIGN KEY (studio) REFERENCES STUDIOS
);

CREATE TABLE ALBUMS (
ISVN       NUMBER(8),
copies	   NUMBER(8) NOT NULL,
total	   NUMBER(8) NOT NULL,
CONSTRAINT PK_ALBUMS PRIMARY KEY (ISVN),
CONSTRAINT FK_ALBUMS FOREIGN KEY (ISVN) REFERENCES DISCS ON DELETE CASCADE
);

CREATE TABLE SINGLES (
ISVN       NUMBER(8),
ISVN_ALB   NUMBER(8) NOT NULL,
CONSTRAINT PK_SINGLES PRIMARY KEY (ISVN),
CONSTRAINT FK_SINGLES1 FOREIGN KEY (ISVN) REFERENCES DISCS ON DELETE CASCADE,
CONSTRAINT FK_SINGLES2 FOREIGN KEY (ISVN_ALB) REFERENCES ALBUMS ON DELETE CASCADE
);

CREATE TABLE RANKINGS (
ISVN       	NUMBER(8),
side		VARCHAR2(1), 
position   	NUMBER(3) NOT NULL,
weeks	   	NUMBER(3) NOT NULL,
CONSTRAINT PK_RANKS PRIMARY KEY(ISVN, side), 
CONSTRAINT FK_RANKS FOREIGN KEY (ISVN) REFERENCES SINGLES ON DELETE CASCADE,
CONSTRAINT CH_RANKS CHECK (side in ('A', 'B'))
);


CREATE TABLE SLEEVES (
ISVN	NUMBER(8),
role	VARCHAR2(80),
side	VARCHAR2(1), 
c_name	VARCHAR2(80), 
CONSTRAINT PK_SLEEVES PRIMARY KEY (ISVN,role,side),
CONSTRAINT FK_SLEEVES FOREIGN KEY (ISVN) REFERENCES DISCS ON DELETE CASCADE,
CONSTRAINT CH_SLEEVES CHECK (side in ('A', 'B'))
);

-- HITS 
CREATE TABLE RADIOS (
name   VARCHAR2(80), 
address VARCHAR2(100) NOT NULL, 
web     VARCHAR2(80) NOT NULL, 
e_mail  VARCHAR2(80) NOT NULL, 
phone   VARCHAR2(9) NOT NULL, 
CONSTRAINT PK_RADIOS PRIMARY KEY (name)
);

CREATE TABLE PLAYBACKS (
station         VARCHAR2(80), 
playdatetime    DATE, 
ISVN       	NUMBER(8),
trackN		NUMBER(2) NOT NULL,
side		VARCHAR2(1) NOT NULL,
CONSTRAINT PK_PLAYBACKS PRIMARY KEY (station, playdatetime),
CONSTRAINT FK_PLAYBACKS1 FOREIGN KEY (station) REFERENCES RADIOS ON DELETE CASCADE,
CONSTRAINT FK_PLAYBACKS2 FOREIGN KEY (ISVN, trackN,side) REFERENCES TRACKS
);

CREATE TABLE CLIENTS (
e_mail      VARCHAR2(100), 
name        VARCHAR2(80) NOT NULL, 
surn1       VARCHAR2(80) NOT NULL, 
surn2       VARCHAR2(80),
birthdate   DATE NOT NULL, 
phone       NUMBER(9) NOT NULL,
address     VARCHAR2(100) NOT NULL, 
DNI         VARCHAR2(8),
CONSTRAINT PK_CLIENTS PRIMARY KEY (e_mail),
CONSTRAINT UK_CLIENTS UNIQUE (DNI));

CREATE TABLE SALE_LINE (
ISVN        NUMBER(8), 
e_mail      VARCHAR2(100), 
order_s     DATE NOT NULL, 
qtty        NUMBER(3), 
delivery    DATE,
CONSTRAINT PK_SALE_LINE PRIMARY KEY (ISVN,e_mail,order_s),
CONSTRAINT FK_SALE_LINE1 FOREIGN KEY (ISVN) REFERENCES DISCS,
CONSTRAINT FK_SALE_LINE2 FOREIGN KEY (e_mail) REFERENCES CLIENTS,
CONSTRAINT CH_SALE_LINE CHECK (order_s<=delivery)
);
